name: ICOZ
favicon: null
layout_spectrum: 0.6749424375593662
typography_spectrum: 0.49453
title: IPTV
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8298ad'
    - '#b0cff2'
    - '#394451'
    - '#32ba34'
  brandStrength: 0.5
  lightness: 0.4710789737291634
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
