typography_spectrum: 0.2973
color:
  brandColors:
    - '#ffffff'
    - '#8298ad'
    - '#b0cff2'
    - '#394451'
    - '#32ba34'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: ICOZ
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About us
    url: 'http://icoz.tv'
    type: external
favicon: null
title: IPTV
purpose: []
